spring:
  main:
    allow-circular-references: true
  datasource:
    url: jdbc:mysql://localhost:3306/lvzz?useUnicode=true&characterEncoding=UTF-8&useSSL=false
    username: root
    password: sa
    driver-class-name: com.mysql.cj.jdbc.Driver
  redis:
    database: 0
    host: 127.0.0.1
    port: 6379
mybatis:
  configuration:
    map-underscore-to-camel-case: true
  mapper-locations: classpath:/mapping/*.xml
  type-aliases-package: com.lvzz.demo.entity
server:
  port: 9001
  servlet:
    context-path: /boot
